export const statsData= [
  {
    title: { en: "Total Sales", ar: "إجمالي المبيعات" },
    subtitle: { en: "Last 7 days", ar: "آخر 7 أيام" },
    value: "$350K",
    change: "10.4%",
    changeLabel: { en: "Sales", ar: "المبيعات" },
    changeType: "increase" as const,
    footerValue: "($235)",
    footerLabel: { en: "Last 7 days", ar: "آخر 7 أيام" },
  },
  {
    title: { en: "Total Orders", ar: "إجمالي الطلبات" },
    subtitle: { en: "Last 7 days", ar: "آخر 7 أيام" },
    value: "10.7K",
    change: "14.4%",
    changeLabel: { en: "Order", ar: "طلب" },
    changeType: "increase" as const,
    footerValue: "(7.6k)",
    footerLabel: { en: "Last 7 days", ar: "آخر 7 أيام" },
  },
  {
    title: { en: "Total Sales", ar: "إجمالي المبيعات" },
    subtitle: { en: "Last 7 days", ar: "آخر 7 أيام" },
    value: "$350K",
    change: "10.4%",
    changeLabel: { en: "Sales", ar: "المبيعات" },
    changeType: "increase" as const,
    footerValue: "($235)",
    footerLabel: { en: "Last 7 days", ar: "آخر 7 أيام" },
  },
];